sudo: required
language: node_js
node_js:
  - "8"
  - "7"
  - "6"
branches:
 only:
   - master
services:
  - mongodb
before_script:
  - echo "replSet = r0" | sudo tee -a /etc/mongodb.conf
  - sudo service mongod restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 25
